name: Tags

on:
  push:
    # Sequence of patterns matched against refs/heads
#    branches:
#      # Push events on main branch
#      - main
#      # Push events to branches matching refs/heads/mona/octocat
#      - 'mona/octocat'
#      # Push events to branches matching refs/heads/releases/10
#      - 'releases/**'
#    # Sequence of patterns matched against refs/tags
    tags:
      - v1             # Push events to v1 tag
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags
      - 1.*.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  labelPR:
    name: With tags
    runs-on: ubuntu-latest
    steps:
      - run: echo Release has happened
      - run: ls -a
